package query

var genresList = map[string]bool{
	// I assume these are the only correct/valid genres
	// https://github.com/prust/wikipedia-movie-data/blob/master/genres.json
	// since this is not huge we can store it in dict
	"action":          true,
	"adventure":       true,
	"animated":        true,
	"biography":       true,
	"comedy":          true,
	"crime":           true,
	"dance":           true,
	"disaster":        true,
	"documentary":     true,
	"drama":           true,
	"erotic":          true,
	"family":          true,
	"fantasy":         true,
	"found footage":   true,
	"historical":      true,
	"horror":          true,
	"independent":     true,
	"legal":           true,
	"live action":     true,
	"martial arts":    true,
	"musical":         true,
	"mystery":         true,
	"noir":            true,
	"performance":     true,
	"political":       true,
	"romance":         true,
	"satire":          true,
	"science fiction": true,
	"short":           true,
	"silent":          true,
	"slasher":         true,
	"sports":          true,
	"spy":             true,
	"superhero":       true,
	"supernatural":    true,
	"suspense":        true,
	"teen":            true,
	"thriller":        true,
	"war":             true,
	"western":         true,
}
